### PR TITLE
Add gitlab discussion and merge request diff support

### PR DESCRIPTION
**Pull request by ManuZiD**
Add support for add discussion to a merge request. Improve code quality and upgrade jackson.

### CODE REVIEW

**Comment by gabrie-allaigre** [comment]
Thanks

**Comment by ManuZiD** [comment]
> Thanks

Please can you provide a release with that pull request? I have a fix for 
https://github.com/gabrie-allaigre/sonar-gitlab-plugin/issues/186

**Comment by mleegwt** [comment]
> > Thanks
> 
> Please can you provide a release with that pull request? I have a fix for
> [gabrie-allaigre/sonar-gitlab-plugin#186](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/issues/186)

@gabrie-allaigre +1 on the release request

Thanks in advance

**Comment by gabrie-allaigre** [comment]
Sorry, I did not make a release, I'm no longer in the company running the maven repository, so I can not publish anymore.
I will use jitpack.io temporarily.

**Pull request merged**
